[package]
name = "TraceHell"
version = "0.1.0"
edition = "2024"

[dependencies]
cargo_metadata = "0.23.1"
prettyplease = "0.3.0"
proc-macro2 = "1.0.107"
syn = { version = "3.0.3", features = ["full", "visit-mut"] }
tempfile = "3.27.0"
walkdir = "2.5.0"


[profile.release]
opt-level = 3
lto = "fat"
strip = "symbols"
panic = "unwind"


# Security-relevant mistakes
mem_forget = "deny"
exit = "warn"
dbg_macro = "deny"
todo = "warn"
unimplemented = "warn"

# Maintainability
large_stack_arrays = "warn"
large_futures = "warn"
needless_pass_by_value = "warn"
redundant_clone = "deny"
