[package]
name = "cargo-tracehell"
version = "0.1.0"
edition = "2024"
description = "small tool to help detect logic errors by showing all ? used"
licence = "Apache-2.0"
repository = "https://github.com/SomeFlyingThing/TraceHell.git"

[dependencies]
anyhow = "1.0.104"
cargo_metadata = "0.23.1"
prettyplease = "0.3.0"
proc-macro2 = "1.0.107"
serde = "1.0.229"
syn = { version = "3.0.3", features = ["full", "visit-mut"] }
tempfile = "3.27.0"
toml = "1.1.4"
walkdir = "2.5.0"


[profile.release]
opt-level = 3
lto = "fat"
strip = "symbols"
panic = "abort"


# Security-relevant mistakes
mem_forget = "deny"
exit = "warn"
dbg_macro = "deny"
todo = "warn"
unimplemented = "warn"

# Maintainability
large_stack_arrays = "deny"
large_futures = "warn"
needless_pass_by_value = "warn"
redundant_clone = "deny"
